name: muon
version: "2.0.0"
summary: Graphical SFTP client and terminal emulator with helpful utilities
description: |
  Muon is a graphical SSH client. It has a file browser,
  terminal emulator, resource/process manager, disk space analyzer, 
  text editor, log viewer and lots of other helpful tools, 
  which makes it easy to work with remote servers.

  More information is available on GitHub Repo: https://github.com/devlinx9/muon-ssh
grade: stable
base: core18
icon: snap/gui/muonssh.png
confinement: strict

apps:
  muon:
    command: java -jar $SNAP/jar/muonssh_2.0.0.jar
    environment:
      # Needed for fontconfig
      XDG_DATA_HOME: ${SNAP}/usr/share
      FONTCONFIG_PATH: ${SNAP}/etc/fonts/config.d
      FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf
    plugs: [x11, ssh-keys,network, desktop, home, network-bind]

parts:
  muon:
    plugin: maven
    source: https://github.com/devlinx9/muon-ssh.git
    build-packages:
      - openjdk-11-jdk
    stage-packages:
      - openjdk-11-jre
      - x11-utils